services:
  - type: web
    name: enterprise-insights-copilot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PORT
        value: 10000
