name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Lint with black
        run: |
          pip install black
          black --check .
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=120 --ignore=E203,W503
      - name: Run tests with coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=backend --cov-report=xml
      - name: Run tests
        run: |
          pytest tests/
